server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://git.coding.net/Merz_Debug/springcloud_demo.git     # 配置git仓库的地址
          search-paths: springcloud-config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号（私有库必填）
          password:                                             # git仓库的密码（私有库必填）
      label: master                                       #配置git仓库的分支
  rabbitmq:
      host: 192.168.199.133
      port: 5672
      username: test
      password: test123

#关闭安全认证
management:
  security:
    enabled: false
  #refresh接入点显式暴露出来
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

